---
# UPS without service credentials 
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceInstance
metadata:
  name: my-ups
  namespace: default
spec:
  forProvider:
    type: user-provided
    name: my-ups
    routeServiceUrl: https://my-route-service.example.com
    syslogDrainUrl: syslog-tls://example.log-aggregator.com:6514
    spaceRef: 
      name: my-space
      policy:
        resolve: Always
