/*
Copyright 2023 SAP SE.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SpaceRoleObservation struct {
	// (String) The date and time when the resource was created in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) format.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) The GUID of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The identity provider for the UAA user.
	Origin *string `json:"origin,omitempty" tf:"origin,omitempty"`

	// (String) The space role type; see [Valid role types](https://v3-apidocs.cloudfoundry.org/version/3.154.0/index.html#valid-role-types).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The date and time when the resource was updated in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) format.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (String) The GUID of the Cloud Foundry user to assign the role to.
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// (String) The username of the Cloud Foundry user to assign the role to.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SpaceRoleParameters struct {
	// (Attributes) Reference to the Cloud Foundry space.
	SpaceReference `json:",inline"`

	// (String) The space role type; see [Valid role types](https://v3-apidocs.cloudfoundry.org/version/3.154.0/index.html#valid-role-types).
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=Developer;Auditor;Manager;Supporter;Developers;Auditors;Managers;Supporters
	Type string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The identity provider for the UAA user.
	// +kubebuilder:validation:Optional
	Origin *string `json:"origin,omitempty" tf:"origin,omitempty"`

	// (String) The username of the Cloud Foundry user to assign the role to.
	// +kubebuilder:validation:Required
	Username string `json:"username,omitempty" tf:"username,omitempty"`
}

// SpaceRoleSpec defines the desired state of SpaceRole
type SpaceRoleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SpaceRoleParameters `json:"forProvider"`
}

// SpaceRoleStatus defines the observed state of SpaceRole.
type SpaceRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SpaceRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SpaceRole is the Schema for the OrgRoles API. Provides a Cloud Foundry resource for assigning org roles.(Updating a role is not supported according to the docs)
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudfoundry}
// +kubebuilder:validation:XValidation:rule="self.spec.managementPolicies == ['Observe'] || (has(self.spec.forProvider.spaceName) || has(self.spec.forProvider.spaceRef) || has(self.spec.forProvider.spaceSelector))",message="SpaceReference is required: exactly one of spaceName, spaceRef, or spaceSelector must be set"
// +kubebuilder:validation:XValidation:rule="[has(self.spec.forProvider.spaceName), has(self.spec.forProvider.spaceRef), has(self.spec.forProvider.spaceSelector)].filter(x, x).size() <= 1",message="SpaceReference validation: only one of spaceName, spaceRef, or spaceSelector can be set"
type SpaceRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SpaceRoleSpec   `json:"spec"`
	Status            SpaceRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SpaceRoleList contains a list of OrgRoles
type SpaceRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SpaceRole `json:"items"`
}

// Repository type metadata.
var (
	SpaceRole_Kind             = "SpaceRole"
	SpaceRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SpaceRole_Kind}.String()
	SpaceRole_KindAPIVersion   = SpaceRole_Kind + "." + CRDGroupVersion.String()
	SpaceRole_GroupVersionKind = CRDGroupVersion.WithKind(SpaceRole_Kind)
)

func init() {
	SchemeBuilder.Register(&SpaceRole{}, &SpaceRoleList{})
}

// GetSpaceRef returns the reference to the space
func (s *SpaceRole) GetSpaceRef() *SpaceReference {
	return &s.Spec.ForProvider.SpaceReference
}
